- hosts: node1.example.com
  remote_user: ansible
  become_user: root
  vars_files:
    - vars/users.yaml

  tasks:
    - name: add user
      become: yes
      user:
        name: "{{ item.value.username }}"
        comment: "{{ item.value.email }}"
        home: "{{ item.value.homedir }}"
        password: "{{ item.value.user_password | password_hash('sha512', 'mysecretsalt') }}"
        update_password: on_create 
      loop: "{{ users | dict2items }}"